# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
after-success:
    - ./travis-tool.sh install_github jimhester/covr
    - Rscript -e 'covr::codecov()'
